import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function OwnerListingsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/auth/login");
  const { data: profile } = await supabase.from("profiles").select("role,status").eq("id", user.id).single();
  if (!profile || profile.role !== "LISTING_OWNER" || profile.status !== "ACTIVE") redirect("/dashboard");

  const { data: listings } = await supabase.from("ad_listings").select("id,title,slug,status,ad_type,city:locations(city:cities(name)),created_at").eq("owner_id", user.id).order("created_at", { ascending: false });

  return <main className="min-h-screen bg-[var(--surface)] text-[var(--ink)]"><header className="border-b border-[var(--border)] bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/owner" className="text-[15px] font-semibold tracking-[0.16em]">YOUR AD SPACE</Link><div className="flex items-center gap-4"><Link href="/listings" className="text-sm text-[var(--slate)]">Marketplace</Link><Link href="/owner/listings/new" className="rounded-xl bg-[var(--ink)] px-4 py-2.5 text-sm font-semibold text-white">Add a space</Link></div></div></header><div className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><p className="text-sm uppercase tracking-[0.16em] text-[var(--muted)]">Inventory</p><div className="mt-2 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="text-4xl font-semibold tracking-[-0.04em]">Your spaces.</h1><p className="mt-3 text-sm text-[var(--slate)]">Manage each advertising placement and its review status.</p></div><p className="text-sm text-[var(--slate)]"><span className="font-semibold text-[var(--ink)]">{listings?.length ?? 0}</span> spaces</p></div><div className="mt-8 overflow-hidden rounded-2xl border border-[var(--border)] bg-white"><div className="grid grid-cols-[1.7fr_1fr_1fr_auto] border-b border-[var(--border)] px-5 py-3 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--muted)]"><span>Space</span><span>Type</span><span>Status</span><span /></div>{(listings ?? []).length === 0 ? <div className="px-5 py-16 text-center"><h2 className="text-xl font-semibold">No spaces yet.</h2><p className="mt-2 text-sm text-[var(--slate)]">Create your first listing to start receiving enquiries.</p><Link href="/owner/listings/new" className="mt-6 inline-flex rounded-xl bg-[var(--ink)] px-5 py-3 text-sm font-semibold text-white">Create listing</Link></div> : (listings ?? []).map((listing) => <div key={listing.id} className="grid grid-cols-[1.7fr_1fr_1fr_auto] items-center gap-4 border-b border-[var(--border)] px-5 py-5 last:border-b-0"><div><p className="font-semibold">{listing.title}</p><p className="mt-1 text-sm text-[var(--slate)]">{(listing.city as { name?: string } | null)?.name ?? "Location pending"}</p></div><p className="text-sm text-[var(--slate)]">{listing.ad_type.replaceAll("_", " ")}</p><span className="w-fit rounded-full bg-[var(--surface)] px-3 py-1.5 text-xs font-semibold">{listing.status.replaceAll("_", " ")}</span><Link href={`/owner/listings/${listing.id}`} className="text-sm font-semibold underline underline-offset-4">Manage</Link></div>)}</div></div></main>;
}
