import { notFound } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

const money = (n: number, currency = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 2 }).format(n || 0);

export default async function QuotePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return <main className="p-8">Please sign in.</main>;
  const { data: quote } = await supabase.from("quotes").select("*").eq("id", id).maybeSingle();
  if (!quote || (quote.advertiser_id !== user.id && quote.owner_id !== user.id)) notFound();
  const { data: items } = await supabase.from("quote_items").select("id,description,quantity,unit_price,amount").eq("quote_id", id).order("id");
  return <main className="mx-auto max-w-4xl px-5 py-10 print:max-w-none print:px-0"><div className="mb-5 flex justify-between print:hidden"><Link href="/dashboard" className="text-sm underline underline-offset-4">Back</Link><button type="button" onClick={() => window.print()} className="text-sm font-medium underline underline-offset-4">Save / print PDF</button></div><article className="border border-[#D1D5DB] bg-white p-8 print:border-0"><header className="flex justify-between gap-8 border-b border-[#E5E7EB] pb-7"><div><p className="text-sm text-[#5F6570]">Your Ad Space</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-[#111318]">QUOTE</h1></div><div className="text-right text-sm"><p className="font-semibold text-[#111318]">{quote.quote_number}</p><p className="mt-1 text-[#5F6570]">{quote.status}</p><p className="mt-1 text-[#5F6570]">Valid until {quote.valid_until || "—"}</p></div></header><section className="grid gap-6 py-7 sm:grid-cols-2"><div><p className="text-xs uppercase tracking-wide text-[#8A9099]">Proposal</p><p className="mt-2 text-sm text-[#111318]">{quote.title || "Outdoor advertising proposal"}</p></div><div className="sm:text-right"><p className="text-xs uppercase tracking-wide text-[#8A9099]">Created</p><p className="mt-2 text-sm text-[#111318]">{quote.created_at ? new Date(quote.created_at).toLocaleDateString("en-IN") : "—"}</p></div></section><table className="w-full text-sm"><thead><tr className="border-y border-[#E5E7EB] text-left text-xs uppercase tracking-wide text-[#8A9099]"><th className="py-3">Description</th><th className="py-3 text-right">Qty</th><th className="py-3 text-right">Unit</th><th className="py-3 text-right">Amount</th></tr></thead><tbody>{(items||[]).map(item=><tr key={item.id} className="border-b border-[#E5E7EB]"><td className="py-4 text-[#111318]">{item.description}</td><td className="py-4 text-right text-[#5F6570]">{item.quantity}</td><td className="py-4 text-right text-[#5F6570]">{money(Number(item.unit_price), quote.currency)}</td><td className="py-4 text-right font-medium text-[#111318]">{money(Number(item.amount), quote.currency)}</td></tr>)}</tbody></table><section className="ml-auto mt-7 max-w-sm space-y-3 text-sm"><div className="flex justify-between"><span className="text-[#5F6570]">Subtotal</span><span>{money(Number(quote.subtotal), quote.currency)}</span></div><div className="flex justify-between"><span className="text-[#5F6570]">Tax ({quote.tax_percent || 0}%)</span><span>{money(Number(quote.tax_amount), quote.currency)}</span></div><div className="flex justify-between border-t border-[#111318] pt-3 text-base font-semibold"><span>Total</span><span>{money(Number(quote.total_amount), quote.currency)}</span></div></section>{quote.notes&&<footer className="mt-10 border-t border-[#E5E7EB] pt-5 text-sm leading-6 text-[#5F6570]">{quote.notes}</footer>}</article></main>;
}
